2019-06-04 20:09:41,751 - E:/github/tmp/log/log_test.py[line:38] - ERROR: error
2019-06-04 20:29:08,013 - E:/github/tmp/log/log_test2.py[line:38] - ERROR: error
2019-06-04 20:29:08,013 - E:/github/tmp/log/log_test2.py[line:38] - ERROR: error
